# Hyprlock color variables
$primary = rgb(8A7B88)           # Primary accent
$on_primary = rgb(c5c4c6)        # Text on primary
$surface = rgb(17151d)           # Surface background
$on_surface = rgb(c5c4c6)        # Text on surface
$error = rgb(61728C)             # Error
$shadow = rgb(000000)                   # Shadow
