# Hyprlock color variables
$primary = rgb(09649C)           # Primary accent
$on_primary = rgb(c2c2c6)        # Text on primary
$surface = rgb(0c0c1e)           # Surface background
$on_surface = rgb(c2c2c6)        # Text on surface
$error = rgb(BFA254)             # Error
$shadow = rgb(000000)                   # Shadow
